# Generated by Django 5.0.7 on 2024-07-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(verbose_name="Дата публикации"),
        ),
    ]
